name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build with Maven
        working-directory: packages/jpaq
        run: mvn clean install -pl :jpaq -am


      - name: Deploy to Nexus
        working-directory: packages/jpaq
        run: mvn --batch-mode flatten:flatten deploy -Pdeploy-nexus --settings ${{ github.workspace }}/settings/settings.xml
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Deploy to GitHub Packages
        working-directory: packages/jpaq
        run: mvn --batch-mode flatten:flatten deploy -Pdeploy-github --settings ${{ github.workspace }}/settings/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}